status:
    project:                 # measuring the overall project coverage
      default:               # context, you can create multiple ones with custom titles
        enabled: yes         # must be yes|true to enable this status
        target: 40%
        threshold: 5%        # allowed to drop X% and still result in a "success" PR status
