include("MINLPs/nlp.jl")
include("MINLPs/blend.jl")
include("MINLPs/brainpc3.jl")
include("MINLPs/castro.jl")
include("MINLPs/circle.jl")
include("MINLPs/convex.jl")
include("MINLPs/discretemulti.jl")
include("MINLPs/div.jl")
include("MINLPs/exprstest.jl")
include("MINLPs/linearlift.jl")
include("MINLPs/multi.jl")
include("MINLPs/rosenbrock.jl")
# include("MINLPs/sincos.jl")
# include("MINLPs/integer.jl")