const POD_C_NLTERMS = [:BILINEAR, :MONOMIAL, :MULTILINEAR, :BININT, :BINLIN, :INTLIN, :BINPROD, :INTPROD, :cos, :sin]
const POD_C_MONOMIAL = [:BILINEAR, :MONOMIAL, :MULTILINEAR]
const POD_C_TRIGONOMETRIC = [:sin, :cos]
